-- AlterTable
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "subscriptionStatus" TEXT NOT NULL DEFAULT 'active';
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "paymentFailedAt" TIMESTAMP(3);
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "paymentFailureReason" TEXT;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "paymentRetryCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "User" ADD COLUMN IF NOT EXISTS "gracePeriodUntil" TIMESTAMP(3);
